### PR TITLE
#35: Improve keyboard interrupt handling in iPython

### LINKED ISSUE #35: iPython notebook keyboard interrupt breaks cell when using Halo
## Description
Currently, in an iPython notebook, if a user does not handle keyboard interrupt and the spinner is running, a `KeyboardInterrupt` is thrown but the spinner keeps spinning.

### System settings

- Operating System: MacOS
- Terminal in use: iTerm 2
- Python version: 2.7.10
- Halo version: 0.0.8

### Expected behaviour
```
In [5]: import time
   ...: import random
   ...:
   ...: spinner.start()
   ...: for i in range(100):
   ...:     spinner.text = '{0}% Downloaded dataset.zip'.format(i)
   ...:     time.sleep(random.random())
   ...: spinner.succeed('Downloaded dataset.zip')
   ...:
⠹ 4% Downloaded dataset.zip^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-5-81a625f23371> in <module>()
      5 for i in range(100):
      6     spinner.text = '{0}% Downloaded dataset.zip'.format(i)
----> 7     time.sleep(random.random())
      8 spinner.succeed('Downloaded dataset.zip')
      9

KeyboardInterrupt:

⠼ 4% Downloaded
```

## Steps to recreate
Following snippet should recreate the error.

```
In [1]: from halo import Halo

In [2]: spinner = Halo(text='Downloading dataset.zip', spinner='dots')

In [3]: import time
   ...: import random
   ...:
   ...: spinner.start()
   ...: for i in range(100):
   ...:     spinner.text = '{0}% Downloaded dataset.zip'.format(i)
   ...:     time.sleep(random.random())
   ...: spinner.succeed('Downloaded dataset.zip')
```

## People to notify
@ManrajGrover

### PR DESCRIPTION
**Pull request by JungWinter**
## Description of changes
This PR resolve the issue #35. In an iPython, if a user rises `KeyboardInterrupt` without handling error statement, the cell is broken and spinner remains.

## Checklist

- [x] Your branch is up-to-date with the base branch
- [x] You've included at least one test if this is a new feature
- [x] All tests are passing

## Related Issues and Discussions
Fixed #35 refer #32

## People to notify
@ManrajGrover

### CODE REVIEW

**Comment by JungWinter** [comment]
@ManrajGrover My windows machine's `tox` is working well. All tests are passed except lint. But why is there a problem on `appveyor`?

**Comment by ManrajGrover** [comment]
Ah, I'm not sure why invocation failed. I just made a PR myself and build passed. I would need to explore it a little more. When you tested it locally on Windows, did all test pass for py27 and py36? If yes, could you please try removing the test case in this PR?

**Comment by JungWinter** [comment]
Yes. Test for py27 and py36 is passed. I updated PR, then `appveyor` is all green.

**Comment by ManrajGrover** [comment]
I would need to see why the test failed on Appveyor. Currently, I don't have access to Windows machine to do the same. Please give me some time to test it on Windows machine. I'm merging this and will add test for this. I'm keeping the issue open as a reminder. Thank you for working on this. 😄 💯

**Pull request merged**
