### PR TITLE
Set the spinner update interval according to the constructor parameter

### PR DESCRIPTION
**Pull request by steelman**
## Description of new feature, or changes
Calling `Halo(interval=1000)` hasn't actually assigned the value to `self._interval`.

## Checklist

- [x] Your branch is up-to-date with the base branch
- [x] All tests are passing

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@steelman Could you please add a test case for this?

**Comment by steelman** [comment]
OK, let me try.

**Comment by steelman** [comment]
```
======================================================================
FAIL: Test proper assignment of the interval value from a dictionary.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\halo\tests\test_halo.py", line 360, in test_spinner_interval_dict
    self.assertEqual(spinner._interval, 321)
AssertionError: 130 != 321
```
Why?

**Comment by JungWinter** [comment]
@steelman  `Halo(spinner={'interval': 321, 'frames': ['+', '-']})` doesn't set `self._interval`.

**Comment by steelman** [comment]
It [does](https://github.com/steelman/halo/blob/d66177bbdfcc46a7440eb4a65d250b60922481d7/halo/halo.py#L55).

**Comment by JungWinter** [comment]
In windows, `self._interval` is default value like 130ms beacause of [this condition](https://github.com/steelman/halo/blob/d66177bbdfcc46a7440eb4a65d250b60922481d7/halo/halo.py#L189)

**Comment by steelman** [comment]
That is why I refer to [default_spinner](https://github.com/steelman/halo/blob/d66177bbdfcc46a7440eb4a65d250b60922481d7/tests/test_halo.py#L29)

**Comment by ManrajGrover** [comment]
We should use the spinner that user provides and move to default if not on Windows as well. I'll create a separate issue for this.

**Comment by ManrajGrover** [comment]
@JungWinter Thank you for looking into this! 😄

**Pull request merged**
