### PR TITLE
Text wrapping and animations

### LINKED ISSUE #1: Spinners breaks when text size exceeds terminal size
Spinners breaks when text size exceeds terminal size. This needs to be fixed with text wrapping.

### PR DESCRIPTION
**Pull request by andreskrey**
Hi,

This kinda fixes #1 (text gets repeated when the text is too long for the terminal) and adds a new functionality: text animations. Like when you wget a large file and the filename scrolls around the terminal.

This new functionality is controlled with the `animations` param. For example:

```
spinner = Halo(text='This is a really large text, testing testing, this is a really large text, testing, testing.', spinner='dots', animation='marquee')
```

I added two animations, which you can see them in action here: https://asciinema.org/a/Z3Q1kMm0iQCQySVD2nuApdMKD

* `marquee` makes the text scroll, just like wget does.
* `bounce` makes it bounce back and forth.

There's a third option, which the code will always default when the text is too large for the terminal: ellipsis. This will truncate the text and add `(...)` at the end. If the user doesn't define an animation and the text is too long, text will be truncated and an ellipsis will be added at the end.

The way this works is by adding the `frames` property to the `self._text` variable. During initialization, the `_get_text` function will create all necessary frames and save them, for later usage. The render approach is pretty much like how the spinner works (using an index to keep track of the displayed frames).

To get the terminal size, I added the `shutil` dependency.

Now, there are a few drawbacks with these changes:

- Text animation framerate is the same as the spinner. Since spinner and text are rendered in the same function, the interval param from the spinner is what defines the text animation speed.
- There's no way to detect if the user resizes the window after launching the spinner
- The `shutil` dependency, AFAIK, is python 3 only and that could be an issue if this project aims to have compatibility with python 2.

I added some unit tests and fixed the current ones to make them work with this new functionality. Feel free to submit any questions or concerns. This is my first approach to python, so I'm sure I'm doing something wrong :)

### CODE REVIEW

**Comment by andreskrey** [comment]
Clearly there are some issues with the CI. Give me a day an I'll fix those :D

**Comment by shardulm94** [comment]
These look awesome. I like the fact that they add extra functionality while fixing the issue. I took a shot at fixing this, my approach was to overflow it onto the next line and clear n lines shardulm94/halo@39788ddbf0ba6eb8c7ca88d57dc411adf5bc616a. The only problems I have had are with compatibility as you rightly mentioned, and resizing terminals. There are ways to get terminal sizes in python2, but there will always be race conditions when resizing terminals.
peek 2017-10-16 20-03

**Comment by andreskrey** [comment]
That's also a great idea. How are you detecting the resize? I wasn't able to deduce that from your code.

**Comment by shardulm94** [comment]
Yeah, the code is not particularly well written. I just wanted to get it working for my specific use case. 
Anyways, I attached a handler to the terminal resize signal, and am recalculating the terminal size whenever I receive the signal [Link](https://github.com/shardulm94/halo/blob/39788ddbf0ba6eb8c7ca88d57dc411adf5bc616a/halo/halo.py#L28).  The signal module only works for unix/linux based systems though. For windows compability, I will have to get rid of `signal`, and recalculate the terminal size at every invocation of clear().

**Comment by andreskrey** [comment]
@ManrajGrover done. Luckly there's a backport for shutil and now all tests pass. Tell me what you think. :)

**Comment by andreskrey** [comment]
1) Weird, I ran those tests locally via Tox and were successful. Same as AppVeyor and Travis CI. Maybe you have something else in your config

2) I know, it solves partly but it's also a new feature.

I do have my concerns with the solutions you proposed. I'll address them below:

1) That's what we currently do. We get the terminal size and build the necessary frames.
2 and 3) It's the best solution, but I have concerns about overhead. Getting the terminal size on every frame and build the frames on every change will have some impact on performance. I will need to do some testing. Maybe a better approach is to build the frames on the fly instead of calculate them beforehand.

What do you think? If the impact on performance is too big, would you be willing to drop the support for Python 2 and use the native -and faster- shutil dependency?

**Comment by ManrajGrover** [comment]
@andreskrey Tests fail if your window size is greater than 80, which is by default. Try changing the terminal width and trying. We need to do option `1` for test cases as well so that they work for all widths. (reason why tests are failing)

I don't think we should add anything that impacts performance, for both Python 2 and Python 3. I would like to explore option `4` a little more. I might be able to do that over the weekend. If you get an opportunity, do try them out.

**Comment by shardulm94** [comment]
After far as I have seen, both those libraries break on terminal resize as well.

**Comment by andreskrey** [comment]
@ManrajGrover I finally managed to reproduce the failing test. Weird thing is that this only happens if I start Tox manually in a small terminal window (I usually do it via Pycharm). I'm not sure what's the difference between that and a normal run (because I cannot reproduce any errors if I use Halo in a normal project). My best guess is that the test run in a different kind of terminal, but not sure how.

I'll do some benchmarks about getting the window size on each frame and come back to you with my findings

@shardulm94 Interesting, we'll see what's the performance impact doing what @ManrajGrover suggested.

**Comment by andreskrey** [comment]
So, this is what I found:

### Test code:

```
from time import *

from halo import Halo

spinner = Halo(text='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sit amet interdum tortor.', spinner='dots', animation='marquee')
spinner.start()
start = time()
for x in range(0, 1000000):
    for y in range(x,10000):
        bla = x*y
spinner.stop()
stop = time()

print(stop - start)
```

### Current PR (average of 5 runs)
4,384 seconds

### Getting the current terminal size on each frame (and recalculating all text frames if the size changed)
4,450 seconds

Not bad! It might feasible then to recalculate frames on the fly. There is one minor issue though:

peek 2017-10-25 01-06

When extending the window the text behaves correctly, but when you shrink it, we have the same issue as before. Any ideas?

**Comment by shardulm94** [comment]
Might be an implementation issue, I had not encountered this when I took a crack at it. Mind sharing the diff/code?

**Comment by andreskrey** [comment]
Sorry, my bad, I thought I pasted the patch. Here it is:

```
Index: halo/halo.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- halo/halo.py	(revision bcc271417cb7728ff22c37e3dbe8b8189e47739a)
+++ halo/halo.py	(revision 1b147fa527a3fa80028939d2334a983b424c1558)
@@ -228,7 +228,8 @@
 
         return {
             'original': text,
-            'frames': frames
+            'frames': frames,
+            'terminal_width': terminal_width
         }
 
     def clear(self):
@@ -289,6 +290,9 @@
         -------
         self
         """
+        if get_terminal_columns() != self._text['terminal_width']:
+            self._text = self._get_text(self._text['original'], 'marquee')
+
         if len(self._text['frames']) == 1:
             # Return first frame (can't return original text because at this point it might be ellipsed)
             return self._text['frames'][0]
```

Nothing fancy, just a quick and dirty way to save some initial information and check the window size on every loop. Of course the 'marquee' part in `text_frame` is assumed. I just need to find a proper place to store that information.

**Comment by shardulm94** [comment]
The problem with this is that when you reduce the terminal size, the data for the previous frame overflows and is split into 2 terminal lines now. So while clearing, you will have to clear 2 lines instead of 1

**Comment by andreskrey** [comment]
@ManrajGrover I'm sorry, I misunderstood what you meant with the tests failing. I just pushed a patch that will measure the terminal size during tests.

What do you think about merging this in and start the discussion about the terminal resize bug in another PR? We can consider this a new feature and avoid discussing two different things in the same comment chain.

**Comment by ManrajGrover** [comment]
@andreskrey I guess that can be done. I would need sometime to review this PR. Sorry for the delay.

**Comment by andreskrey** [comment]
No rush, thanks :)

**Comment by JungWinter** [comment]
Isn't any update here?

**Comment by ManrajGrover** [comment]
@JungWinter Thanks for pinging!

@andreskrey Thank you for the pull request! Apologies for the delay in getting back on this. This LGTM in general, although the tests fail for me on full screen. This is because text we are using to test on is not as long as the terminal width. I'll make the required changes. Merging this! 💯

**Comment by ManrajGrover** [comment]
@JungWinter This is now released in v0.0.8. 😄

**Pull request merged**
