### PR TITLE
BUG: Halo install requires UTF-8 locale to be set

### LINKED ISSUE #124: Bug: Halo install requires UTF-8 locale to be set
Thank you for the software. I recently added it to an internal tool and now am installing Halo on CI.

I hit this issue when installing Halo on some CI machines.
Some systems do not have UTF-8 set as the default locale.
Halo does not work in these cases.
This is because "README.md" is a UTF-8 encoded file, but `open()` uses the default encoding.

One way to reproduce this is with Docker:

```
$ docker run -it ubuntu /bin/bash

# apt-get -qq update
# apt-get -qq install -y python3 python3-pip
# python3 -c 'import locale; print(locale.getpreferredencoding(False))'
ANSI_X3.4-1968 # << Note, this is not UTF-8
# pip3 install halo
Collecting halo
  Downloading https://files.pythonhosted.org/packages/d5/14/e2b6180addc38803b8170afb798a06c2e407e79efb8e14591e8820e718d3/halo-0.0.23.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5gyk692_/halo/setup.py", line 10, in <module>
        long_description = infile.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3604: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5gyk692_/halo
```

### PR DESCRIPTION
**Pull request by adamtheturtle**
## Description of new feature, or changes

See #124 for the issue that this fixes.
This change has been tested with the test set out in that issue.

## Checklist

- [X] Your branch is up-to-date with the base branch
- [X] You've included at least one test if this is a new feature: This is not a new feature.
- [ ] All tests are passing: I hope they will!

## Related Issues and Discussions

Fixes #124 .

## People to notify

@manrajgrover

### CODE REVIEW

**Comment by juledwar** [comment]
I think my fix still has something you need - it ensures the README is opened read-only, which is missing from the old code and #125 

Thanks for sorting it out anyway!

**Comment by manrajgrover** [comment]
@juledwar Ah, makes sense. I'll make that change in some time. For now, I've made the release for this.

https://pypi.org/project/halo/0.0.24/

**Comment by juledwar** [comment]
@manrajgrover Thanks! Is there any chance you can release log-symbols 0.0.13 as well and release Halo again to use it? It has the important enum34 fix!

**Comment by manrajgrover** [comment]
@juledwar Looking into it. Thanks for pointing it out. I've been a lot occupied lately and had decided to squash and sort out everything today. :smile:

**Comment by manrajgrover** [comment]
@juledwar Made a release and updated halo to v0.0.25! This should be fixed now.

**Pull request merged**
