### PR TITLE
Add installation note for Arch Linux.

### PR DESCRIPTION
**Pull request by goggle**
## Description of new feature, or changes

Update README.md: Add note that the package is available in the Arch User Respository. I have created a package for python-halo in the AUR. If you don't want to mention that in the README, simply close that PR.

## Checklist

- [x] Your branch is up-to-date with the base branch
- [x] You've included at least one test if this is a new feature
- [x] All tests are passing

### CODE REVIEW

**Comment by manrajgrover** [comment]
Hi @goggle,

Thanks for the PR. How does this work? If I merge features, fixes and other things in this project, how will Arch User Repository update?

**Comment by goggle** [comment]
@manrajgrover I will maintain the AUR package, i.e. adopt the PKGBUILD (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-halo), which basically just are build instructions. When you release a new version of halo, I must update the PKGBUILD, so that the Arch Linux users will be able to install the new version of halo from the AUR. For small changes in the project this is a very easy task for me, I just have to change the version number and the hash in the PKGBUILD. If you add or remove dependencies, it would be nice to mention this in a release changelog, so that I don't forget to add/remove them too in the PKGBUILD.

**Comment by manrajgrover** [comment]
@goggle I'm still thinking about it. It is tough to guarantee this. If there is an automated way using which we can deploy to pypi and AUR together, I'm up for this. But currently, this seems an overhead.

**Comment by goggle** [comment]
@manrajgrover What exactly do you think is tough to guarantee? Having a changelog with each release? If so, it's not that much of a problem, because you `requirements.txt` file, which contains all the dependencies. So actually it wouldn't even be necessary. 

Many smaller projects on github (who hope to get bigger) have install instructions for various Linux distributions (Arch, Debian, Fedora, Ubuntu, etc.) in their `README.md`. This is useful to know for users (who don't want to install it through pip, because this can cause problems with the Python packages that are installed through the system package manager) and for developers who want to write software using `halo` as a dependency, because they see that `halo` is easily available in different Linux distributions, so it's easy to create a package of their software for these distributions.

Is there already a somewhat popular tool which uses `halo` as a dependency out there?

**Pull request closed without merging**
