### PR TITLE
Demos: Move demo gifs to svg based demos

### LINKED ISSUE #37: Demos: Move demo gifs to svg based demos
## Description
Currently, we make use of gif demos, which is cool, but not as cool as `svg-term-cli`. Need to explore and move demos to svg based terminal sessions to improve documentation.

### PR DESCRIPTION
**Pull request by 0scarB**
## Description of new feature, or changes

Changes demo GIFs to SVGs in the `README.md` using SVGs generated by [svg-term-cli](https://github.com/marionebl/svg-term-cli).

## Checklist

- [x] Your branch is up-to-date with the base branch
~- [ ] You've included at least one test if this is a new feature~
- [x] All tests are passing

## Related Issues and Discussions

Resolves #37

## People to notify

@manrajgrover

### CODE REVIEW

**Comment by manrajgrover** [comment]
@0scarB Hi, thanks for fixing this. There seems to be a gap between emoticons and text. Is it normal or something wrong in the code?

**Comment by 0scarB** [comment]
No problem :smiley: I thinks the gap might have something to do with the glyphs in the font `svg-term-cli` is using i.e. some glyphs are wider than other.

**Comment by manrajgrover** [comment]
@0scarB Can you remove the extra space in example codes and generate the SVG again? This will help keep text aligned.

https://github.com/manrajgrover/halo/blob/master/examples/doge_spin.py#L24

**Comment by 0scarB** [comment]
Good suggestion :+1: Let me know what you think about the result.

**Pull request merged**
