### PR TITLE
Feature #32: Available Halo in jupyter notebook

### PR DESCRIPTION
**Pull request by JungWinter**
## Description of new feature
Now, Halo in `jupyter notebook` is available by implementing `IPython widget`. If you want, test manually [on `.ipynb`](https://github.com/JungWinter/halo/blob/feature-notebook/examples/notebook.ipynb)(require download).

capture-gif

## Checklist

- [x] Your branch is up-to-date with the base branch
- [x] You've included at least one test if this is a new feature
- [x] All tests are passing

## Opinion
I tried to find the way that can test `IPython widget` in unittest. I searched the `tqdm`, but they skip tests related with `tqdm_notebook`. So in this PR, I exclude `halo_notebook.py` from coverage by modifying `.coveragerc` file. And linting test isn't still working on my machine. :( 

I have no experience with Python packaging, so I'm not sure it's ok to add dependency about `ipywidgets`. Please tell me what to do.

## Related Issues and Discussions
Discuss on #32 

## People to notify
@ManrajGrover

### CODE REVIEW

**Comment by JungWinter** [comment]
@ManrajGrover  Isn't any update here?

**Comment by ManrajGrover** [comment]
@JungWinter I had faced the similar issue in lint but I thought it was fixed. It was because of some compatibility issue between Python2.7 and Python3.6. Looks like I would need to do a little debugging on it. See if you can reproduce the error on Python2.7.

The initial code looks great. I just tested it locally and it seems to work. I still need a little more time for reviewing the code though. Thanks for working on this. 😄 💯

**Comment by ManrajGrover** [comment]
Regarding `ipywidgets`, since it is a requirement of Halo_Notebook, we need to add it to requirements. We can skip tests for this, but we should surely test any utilities being added.

**Comment by JungWinter** [comment]
@ManrajGrover Thanks for the comment. I'll try to add tests for `HaloNotebook`. Maybe It looks like to check `self.output.outputs` of `HaloNotebook` class. 🚀

**Comment by JungWinter** [comment]
@ManrajGrover How about this way when testing `HaloNotebook`?

**Comment by ManrajGrover** [comment]
@JungWinter Just to let you know, I'm reviewing this in parts and that currently, this looks great. 

Regarding testing the code, is there any other way to get the output that is being rendered? Because currently, this only tests the output of the code and not what is being rendered.

**Comment by JungWinter** [comment]
@ManrajGrover Thanks for reviewing! As I know, this is the only way to test the output of `ipywidget` to be rendered. The `outputs` variable of the `Output` class matches the rendered output shown in the jupyter cell. I think it's not much different from the current way to read and seek `_stream`. If there is any way to test rendered output, I'll update my PR!

**Comment by JungWinter** [comment]
@ManrajGrover Isn't any update here?

**Comment by ManrajGrover** [comment]
@JungWinter This is on high priority for me and I'll definitely finish reviewing and merging ASAP. Really sorry for the delay. Thanks for pinging.

**Pull request merged**
