### PR TITLE
Right spinner: Adds an option to place the spinner on the right side of the text

### PR DESCRIPTION
**Pull request by stephen-bunn**
## Description of new feature, or changes
Adds a flag that places the spinner to the right of the text.

```python
with Halo(text='Spinning...', right=True) as spinner:
    # stuff...

Spinning... ⠧
```

Also affects the `stop_and_persist` methods.

## Checklist

- [x] Your branch is up-to-date with the base branch
- [x] You've included at least one test if this is a new feature
- [x] All tests are passing

## Related Issues and Discussions
I don't think there has been any discussions or issues related to this feature.

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@stephen-bunn Hi, I'm not sure if I would like to include this feature. Any particular reason or use case where this would be needed?

**Comment by stephen-bunn** [comment]
Feel free to close the pull request if you don't think it should be a feature.

One of the reasons I choose not to use halo is the missing functionality to place the spinner on the right side of the text. I simply opened a pull request instead of an issue because it seemed trivial to implement.

**Comment by ManrajGrover** [comment]
@stephen-bunn It won't be as trivial as it sounds because we support ellipses for long texts. If someone uses that feature with this option, it would give undesirable results. Hence, I would love to know your use case for this feature since I cannot think of any.

**Comment by stephen-bunn** [comment]
Ah I see, there is no real use case for having the spinner on the right side of the text. It is just a style choice I would like to have.

**Comment by ManrajGrover** [comment]
@stephen-bunn Looks like others are also interested in this feature. Are you still willing to take this one up? Let me know and I'll review. One change I would want is renaming the `right` keyword to `placement` and making it a string with default `left`. I'll review the code if you're willing to continue. Thanks for working on this and apologies for the delay.

**Comment by stephen-bunn** [comment]
@ManrajGrover sure thing, I've opened a **new** PR since the repo for this one has been removed.
Now the text values `left` and `right` are accepted by a parameter called `placement`.

Closing this PR due to revisions in #57.

**Pull request closed without merging**
